version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: korobkin66/foodgram_backend
    env_file: ../backend/foodgarm/.env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
    restart: on-failure
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
