# Generated by Django 4.2.7 on 2024-01-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_remove_recipe_ingredients_recipe_quantities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quantities',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.quantity', verbose_name='Количество ингредиентов'),
        ),
    ]
