# Generated by Django 4.2.7 on 2024-01-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_quantities_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='quantities',
        ),
    ]
