# Generated by Django 4.2.7 on 2024-01-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_rename_ingredients_recipe_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='quantities',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
