# Generated by Django 4.2.7 on 2024-01-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_recipe_quantities_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.Quantity', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
